---
layout: default 
title: "1088 - AWS Lambda functions are widely used in "
---


[.question]
== 1088-64a1df5faa736d27b1db9454.


****

[.query]
--
AWS Lambda functions are widely used in your company by different teams.
There is a requirement to extend the Lambda functions to integrate with other tools for monitoring, observability and security such as AppDynamics, HashiCorp, Splunk, etc.
With the integration, some additional code needs to be run during function initialization, invocation or shut down.
Which of the following options can achieve the requirement by extending Lambda's execution environment?


--

[.list]
--
* [*] A. Deploy Lambda extensions through Lambda layers by adding the extensions in the Lambda .zip archives.
* [ ] B. Deploy the required tools in other dedicated Lambda functions and integrate existing Lambda functions with these dedicated Lambda functions.
* [*] C. Extend Lambda function with CloudWatch event rules by configuring third-party Lambda functions to process events.
* [ ] D. Integrate the Lambda function with Amazon SQS and process the queue messages by Lambda extensions.

--
****

[.answer]
Correct Answer A

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer: A.
Option A is CORRECT because Lambda Extensions provides an easy way to integrate Lambda with other tools.
The Lambda Extensions can be deployed through Lambda Layers that are generated by the .zip archive files.
Lambda service extracts the extension files from the Lambda layers and manages the lifecycle of extensions.
Option B is incorrect because there is no need to create other Lambda functions.
The existing Lambda functions should be extended by Lambda Extensions.
Option C is incorrect because CloudWatch event rules cannot trigger additional code during function initialization or shut down.
Creating extra Lambda functions is not necessary.
Option D is incorrect because Lambda extensions cannot be used to process SQS messages from Lambda functions.
SQS queues are not required for building extensions for AWS Lambda.
References:
https://aws.amazon.com/blogs/compute/building-extensions-for-aws-lambda-in-preview/, https://docs.aws.amazon.com/lambda/latest/dg/using-extensions.html
Lambda extensions are a way to integrate Lambda functions with tools for monitoring, observability, and security. They allow for additional code to be run during function initialization, invocation, or shut down. There are different options to extend Lambda's execution environment, and the question asks which one can achieve the requirement of integrating Lambda with other tools.
A. Deploy Lambda extensions through Lambda layers by adding the extensions in the Lambda .zip archives.
Lambda layers are a way to manage common code and libraries across multiple Lambda functions. They allow you to package and deploy external dependencies that can be used by your function code. While it is possible to add Lambda extensions to a Lambda layer and deploy it with the function code, this option does not allow for a specific initialization or shut down order, as the layer is loaded alongside the function code. This option is not ideal if the additional code needs to run during a specific phase of the function execution.
B. Deploy the required tools in other dedicated Lambda functions and integrate existing Lambda functions with these dedicated Lambda functions.
This option suggests deploying other Lambda functions that handle the integration with the required tools. While it is possible to do this, it adds complexity to the system and creates additional overhead, as it requires invoking multiple functions to complete the same task. This option is not optimal for performance and maintenance reasons.
C. Extend Lambda function with CloudWatch event rules by configuring third-party Lambda functions to process events.
CloudWatch event rules allow you to define events that trigger the execution of a Lambda function. This option suggests configuring third-party Lambda functions to process events and trigger the extension code. While this option may work for some scenarios, it may not be suitable for situations where the function needs to run the additional code during initialization or shut down.
D. Integrate the Lambda function with Amazon SQS and process the queue messages by Lambda extensions.
This option suggests using Amazon SQS as a buffer to process messages containing the additional code to be executed during function initialization, invocation, or shut down. SQS can act as a trigger for Lambda, which can then process the messages and execute the additional code. This option allows for precise control over when the code is executed and provides a scalable and reliable way to handle the integration with the required tools.
In conclusion, option D is the best approach to achieve the requirement of extending Lambda's execution environment by integrating it with other tools for monitoring, observability, and security.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question419:"link"


