---
layout: default 
title: "953 - Your company produces customer commissio"
---


[.question]
== 953-64a1df2eaa736d27b1db9388.


****

[.query]
--
Your company produces customer commissioned one-of-a-kind skiing helmets combining high fashion with custom technical enhancements.
Customers can show off their individuality on the ski slopes and have access to head-up-displays.
GPS rear-view cams and any other technical innovation they wish to embed in the helmet.
The current manufacturing process is data-rich and complex, including assessments to ensure that the custom electronics and materials used to assemble the helmets are the highest standards.
Assessments are a mixture of human and automated assessments.
You need to add a new set of assessments to model the electronics' failure modes using GPUs with CUDA across a cluster of servers with low latency networking.
What architecture would allow you to automate the existing process using a hybrid approach and ensure that the architecture can support the evolution of processes over time?


--

[.list]
--
* [*] A. Use AWS Data Pipeline to manage the movement of data & meta-data and assessments. Use an Auto Scaling group of G2 instances in a placement group.
* [*] B. Use AWS Step Functions to manage assessments, movement of data, & meta-data. Use an Auto Scaling group of G2 instances in a placement group.
* [ ] C. Use Amazon Simple Workflow (SWF) to manage assessments movement of data & meta-data. Use an Auto Scaling group of C3 instances with SR-IOV (Single Root I/O Virtualization).
* [ ] D. Use AWS data Pipeline to manage the movement of data & meta-data and assessments. Use an Auto Scaling group of C3 with SR-IOV (Single Root I/O virtualization).

--
****

[.answer]
Answer  B

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - B.
The main point to consider in this question is that the assessments include human interaction as well.
In most such cases, always look for AWS Step Functions in the options.
Option A is incorrect because this will be useful during the batch jobs, which deal with the automated assessments.
For the human assessment, this will not be a useful option.
Option B is CORRECT because (a)it enables assessment via human interaction, (b) uses Auto Scaled G2 instances that are efficient in automated assessments due to their GPU and low latency networking.
Please refer the below link for AWS Step Functions.
https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html
Option C is incorrect because although SWF can be used for human tasks, C3 instances and SR-IOV will not provide the required GPU.
Option D is incorrect because (a) this will be useful during the batch jobs, which deal with the automated assessments.
This will not be a useful option for the human assessment, and (b) C3 instances and SR-IOV will not provide the required GPU.
To automate the existing process of adding a new set of assessments for modeling electronics failure modes using GPUs with CUDA across a cluster of servers with low latency networking and ensure that the architecture can support the evolution of processes over time, we need an architecture that provides scalability, high availability, and fault tolerance.
Option A: Use AWS Data Pipeline to manage the movement of data & metadata and assessments. Use an Auto Scaling group of G2 instances in a placement group.
AWS Data Pipeline is a web service that allows you to move data between different AWS services, such as Amazon S3, Amazon RDS, and Amazon DynamoDB. It can also be used to automate the execution of data-driven workflows. In this option, we can use AWS Data Pipeline to manage the movement of data and metadata and assessments. However, G2 instances are designed for graphics-intensive workloads and not for GPU-based computing, which is required for this scenario. Also, G2 instances are based on an older architecture and have limited scalability, which makes this option less suitable for the task.
Option B: Use AWS Step Functions to manage assessments, movement of data, and metadata. Use an Auto Scaling group of G2 instances in a placement group.
AWS Step Functions is a serverless workflow service that allows you to coordinate the components of distributed applications and microservices. It provides visual workflows to build and run applications using AWS services like AWS Lambda, Amazon SNS, and Amazon SQS. In this option, we can use AWS Step Functions to manage assessments, movement of data, and metadata. However, G2 instances are not suitable for this scenario, as explained above.
Option C: Use Amazon Simple Workflow (SWF) to manage assessments, movement of data, and metadata. Use an Auto Scaling group of C3 instances with SR-IOV (Single Root I/O Virtualization).
Amazon SWF is a workflow service for building scalable, distributed applications. It can be used to coordinate the execution of tasks across multiple machines and services, allowing you to build complex, multi-step workflows. In this option, we can use Amazon SWF to manage assessments, movement of data, and metadata. C3 instances with SR-IOV are optimized for compute-intensive workloads and provide high network performance. They can also be used for GPU-based computing, which makes this option suitable for the task.
Option D: Use AWS Data Pipeline to manage the movement of data & metadata and assessments. Use an Auto Scaling group of C3 with SR-IOV (Single Root I/O virtualization).
This option is similar to Option C, but it uses AWS Data Pipeline instead of Amazon SWF to manage the movement of data and metadata and assessments. AWS Data Pipeline can be used to automate the execution of data-driven workflows, making it a suitable alternative to Amazon SWF. However, Amazon SWF is more flexible and provides greater control over the workflow execution.
In summary, Option C or Option D would be the most suitable options for the scenario described. Both options use a combination of Amazon SWF or AWS Data Pipeline and an Auto Scaling group of C3 instances with SR-IOV to provide scalability, high availability, and fault tolerance. The choice between the two options will depend on the specific requirements of the workflow and the preferences of the solution architect.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question214:"link"


