---
layout: default 
title: "1082 - Your company is running a business analy"
---


[.question]
== 1082-64a1df5daa736d27b1db944c.


****

[.query]
--
Your company is running a business analytics service that uses RDS with MySQL as the main database.
The database is configured with Multi-AZ.
Most recently, the load on the database has increased rapidly with the launch of new features.
By looking at the logs, most of the load is generated by the read-only queries.
Because of the heavy read loads, the operations team has decided to put a set of read-replicas in place.
The new application features are launched via a cluster of containers into the virtual machines, where all the containers are having access to the same set of configurations.
How can you pair the read replicas together to make sure the application running in the containers can access them properly?


--

[.list]
--
* [*] A. Create Amazon Route 53 weighted record sets to distribute requests across the read replicas.
* [ ] B. Create an ELB and point to all the read replicas. Use the URL of the ELB to access the read replicas from the application.
* [*] C. Create an Elastic IP and create a route table entry to point the IP to the read replicas. Use the IP to access the read replicas from the application.
* [ ] D. Read replica cluster is not supported in AWS. Use an external utility to create a DNS record and use the record to access the read replicas from the application.

--
****

[.answer]
Correct Answer A

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer: A.
Option A is CORRECT because, in Route 53, you can create individual record sets for each DNS endpoint associated with your read replicas and give them the same weight.
Then the read requests are distributed across multiple read replicas.
Option B is INCORRECT because the ELB cannot point to multiple replicas.
Option C is INCORRECT because this is not a workable solution.
Elastic IP is an external resource, and routing the Elastic IP to read replica set is impossible.
Option D is INCORRECT because it is possible to route internal Route53 multivalve answer records to a set of IPs.
In this scenario, the operations team has decided to use read replicas to handle the heavy read loads generated by the new application features. Read replicas in Amazon RDS provide read scaling for database workloads. Read replicas allow you to create one or more copies of your database that are in sync with the primary instance. Read replicas can be promoted to become the primary instance in the event of a primary failure, and they can also be used to offload read traffic from the primary instance.
The question asks how to pair the read replicas together so that the application running in the containers can access them properly. There are a few options for achieving this:
A. Create Amazon Route 53 weighted record sets to distribute requests across the read replicas. This option involves using Amazon Route 53, a DNS service that can be used to route traffic to different resources based on various rules. Weighted record sets allow you to distribute traffic across multiple resources in proportion to their weights. In this case, you could create a weighted record set that points to each read replica, with a weight that reflects its capacity to handle read traffic. The application running in the containers could then use the DNS name associated with the weighted record set to access the read replicas.
B. Create an ELB and point to all the read replicas. Use the URL of the ELB to access the read replicas from the application. This option involves using an Elastic Load Balancer (ELB) to distribute traffic across the read replicas. An ELB can be configured with a set of targets (in this case, the read replicas), and it will distribute incoming traffic across them using a round-robin algorithm. The application running in the containers could then use the URL associated with the ELB to access the read replicas.
C. Create an Elastic IP and create a route table entry to point the IP to the read replicas. Use the IP to access the read replicas from the application. This option involves using an Elastic IP (EIP), which is a static IP address that can be associated with an AWS resource, such as an EC2 instance or an RDS instance. By creating a route table entry that points to the EIP, traffic can be routed to the read replicas. The application running in the containers could then use the EIP to access the read replicas.
D. Read replica cluster is not supported in AWS. Use an external utility to create a DNS record and use the record to access the read replicas from the application. This option is incorrect because read replica clusters are supported in AWS. Also, it is not necessary to use an external utility to create a DNS record, as AWS provides DNS services such as Route 53 that can be used for this purpose.
In conclusion, options A, B, and C are all viable solutions for pairing the read replicas together so that the application running in the containers can access them properly. The best option will depend on the specific requirements of the application and the resources available.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question411:"link"


