---
layout: default 
title: "1015 - Your customer is implementing a videoond"
---


[.question]
== 1015-64a1df45aa736d27b1db93ea.


****

[.query]
--
Your customer is implementing a video-on-demand streaming platform on AWS.
The requirement is to be able to support multiple devices such as iOS, Android, and Windows as client devices, using a standard client player, using streaming technology and scalable architecture with cost-effectiveness.


--

[.list]
--
* [*] A. Store the video contents to Amazon Simple Storage Service (S3) as an origin server. Configure the Amazon CloudFront distribution with a streaming option to stream the video contents.
* [*] B. Store the video contents to Amazon S3 as the origin server. Configure the Amazon CloudFront distribution. Use the AWS Elemental MediaConvert to easily create video-on-demand (VOD) content for broadcast and multiscreen delivery ( multi- devices) at scale.
* [ ] C. Launch a streaming server on Amazon Elastic Compute Cloud (EC2) (for example, Adobe Media Server), and store the video contents as an origin server. Configure the Amazon CloudFront distribution with a download option to stream the video contents.
* [ ] D. Launch a streaming server on Amazon EC2 (for example, Adobe Media Server), and store the video contents as an origin server. Launch and configure the required amount of streaming servers on Amazon EC2 as an edge server to stream the video contents.

--
****

[.answer]
Answer  B

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - B.
Option A is incorrect because it uses CloudFront distribution with the streaming option which does not work on all platforms; whereas, it should use the download option.
Option B is CORRECT because (a) it uses CloudFront distribution (b) It uses Elemental MediaConvert for streaming the on-demand videos on any mobile and (c) it uses S3 as origin, so it keeps the costs low.
Option C is incorrect because (a) provisioning streaming EC2 instances is a costly solution, (b) the videos are to be delivered on-demand, not live streaming.
Option D is incorrect because the videos are to be delivered on-demand, not live streaming.
So, the streaming server is not required.
For more information on live and on-demand streaming using CloudFront, please visit the below URL:
https://aws.amazon.com/blogs/aws/using-amazon-cloudfront-for-video-streaming/
Note:
In the on-demand streaming case, your video content is stored in Amazon S3
Viewers can choose to watch it at any desired time.
A complete on-demand streaming solution typically uses Amazon S3 for storage, AWS Elemental MediaConvert for file-based video processing, and Amazon CloudFront for delivery.
Once uploaded, you may need to convert your video into the size, resolution, or format needed by a particular television or connected device.
AWS Elemental MediaConvert will take care of this for you.
MediaConvert takes content from S3, transcodes it as requested, and stores the result back in S3
Transcoding processes video files, creating compressed versions of the original content to reduce its size, change its format, or increase playback device compatibility.
You can also create assets that vary in resolution and bitrate for adaptive bitrate streaming, which adjusts the viewing quality depending on the viewer's available bandwidth.
AWS Elemental MediaConvert outputs the transcoded video to an S3 bucket.
The next step is global delivery with Amazon CloudFront.
CloudFront caches content at the edges for low latency and high throughput video delivery.This delivery can be made in two different ways.
You can deliver the entire video file to the device before playing it, or you can stream it to the device.
More information is available at:
https://aws.amazon.com/cloudfront/streaming/ https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/on-demand-video.html
Video streaming requires a scalable and cost-effective architecture to deliver content to multiple devices across different platforms. AWS provides a variety of services that can be used to meet the requirements of the client.
Option A: Store the video contents to Amazon S3 as an origin server. Configure the Amazon CloudFront distribution with a streaming option to stream the video contents. Amazon S3 is a highly scalable, reliable, and durable object storage service. It can be used as an origin server to store the video content. Amazon CloudFront is a content delivery network (CDN) that can be used to deliver the video content to end-users. With the streaming option enabled, CloudFront can deliver video content to a variety of devices, including iOS, Android, and Windows. This option is cost-effective, scalable, and easy to manage.
Option B: Store the video contents to Amazon S3 as the origin server. Configure the Amazon CloudFront distribution. Use the AWS Elemental MediaConvert to easily create video-on-demand (VOD) content for broadcast and multiscreen delivery (multi-devices) at scale. This option is similar to Option A, but it uses AWS Elemental MediaConvert to create video-on-demand content for broadcast and multiscreen delivery. MediaConvert is a file-based video transcoding service that can be used to convert video content into various formats and resolutions. This option provides additional flexibility to create VOD content for broadcast and multiscreen delivery, but it may be more expensive than Option A.
Option C: Launch a streaming server on Amazon EC2 (for example, Adobe Media Server), and store the video contents as an origin server. Configure the Amazon CloudFront distribution with a download option to stream the video contents. This option uses Amazon EC2 to launch a streaming server (e.g. Adobe Media Server) and store the video content as an origin server. Amazon CloudFront is used to deliver the video content to end-users with the download option enabled. This option may be more expensive than Option A or B since it requires the deployment and management of a streaming server.
Option D: Launch a streaming server on Amazon EC2 (for example, Adobe Media Server), and store the video contents as an origin server. Launch and configure the required amount of streaming servers on Amazon EC2 as an edge server to stream the video contents. This option is similar to Option C, but it uses multiple streaming servers as edge servers to deliver the video content to end-users. This option provides additional scalability and reliability, but it may be more expensive than Option A or B.
In conclusion, the best option for implementing a video-on-demand streaming platform on AWS is Option A. It provides a cost-effective, scalable, and easy-to-manage solution using Amazon S3 as the origin server and Amazon CloudFront as the CDN with the streaming option enabled. Option B may be more flexible, but it may also be more expensive. Options C and D may provide additional scalability and reliability, but they may also be more expensive and complex to manage.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question313:"link"


