---
layout: default 
title: "1074 - A user is using a small MySQL RDS DB
The"
---


[.question]
== 1074-64a1df5baa736d27b1db9444.


****

[.query]
--
A user is using a small MySQL RDS DB.
The user is experiencing high latency due to the Multi-AZ feature.
Which of the below mentioned options may NOT help the user in this situation?


--

[.list]
--
* [*] A. Schedule the automated backup in non-working hours.
* [ ] B. Use a large or higher size instance.
* [ ] C. Use Provisioned IOPS storage.
* [*] D. Take a snapshot from standby Replica.

--
****

[.answer]
Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - D.
Option A is INCORRECT since scheduling automatic back-ups in non-working hours will help reduce the high latency that the user is experiencing.
The question is asking for a NOT option.
Therefore this option is incorrect.
Option B is INCORRECT because using a larger or a higher instance size will reduce the latency due to the multi-AZ feature.
Option C is INCORRECT because using the provisioned IOPS, the users would get high throughput from the DB instance.
The question is asking for a NOT option.
Therefore this option is incorrect.
Option D is CORRECT because taking a snapshot from a standby replica would not help to reduce the latency.
###########################
Amazon RDS Basic Operational Guidelines.
The following are basic operational guidelines that everyone should follow when working with Amazon RDS.
Note that the Amazon RDS Service Level Agreement requires that you follow these guidelines.
Monitor your memory, CPU, and storage usage.
Amazon CloudWatch can be set up to notify you when usage patterns change or when you approach your deployment capacity so that you can maintain system performance and availability.
Scale up your DB instance when you are approaching storage capacity limits.
You should have some buffer in storage and memory to accommodate unforeseen increases in demand from your applications.
Enable automatic backups and set the backup window to occur during the daily low in write IOPS.
If your database workload requires more I/O than you have provisioned, recovery after a failover or database failure will be slow.
To increase the I/O capacity of a DB instance, do any or all of the following:
Migrate to a DB instance class with High I/O capacity.
Convert from standard storage to either General Purpose or Provisioned IOPS storage, depending on how much of an increase you need.
For information on available storage types, see Amazon RDS Storage Types.
If you convert to Provisioned IOPS storage, make sure you also use a DB instance class that is optimized for Provisioned IOPS.
For information on Provisioned IOPS, see Provisioned IOPS SSD Storage.
If you are already using Provisioned IOPS storage, provision additional throughput capacity.
###########################
For more information on Multi-AZ RDS, please visit the link:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_BestPractices.html
The Multi-AZ feature in Amazon RDS (Relational Database Service) is a feature that automatically replicates a user's primary database in a different availability zone to provide high availability and failover support. When a user's primary database becomes unavailable, the failover process is triggered and the secondary replica is promoted to become the new primary database.
If the user is experiencing high latency due to the Multi-AZ feature, there could be several reasons for it. For example, the user's application may be configured to connect to the primary database, and if there is a failover event, the application will need to re-establish a connection to the new primary database, which could cause latency. Additionally, the replication process between the primary and secondary database could also cause latency.
Let's go through the options and see which of them may not help the user in this situation:
A. Schedule the automated backup in non-working hours: This option may help the user in reducing the load on the database during working hours, but it may not necessarily help with the latency issue caused by the Multi-AZ feature.
B. Use a large or higher size instance: This option may help the user in improving the performance of the database, but it may not necessarily help with the latency issue caused by the Multi-AZ feature.
C. Use Provisioned IOPS storage: This option may help the user in improving the I/O performance of the database, but it may not necessarily help with the latency issue caused by the Multi-AZ feature.
D. Take a snapshot from standby Replica: This option may also help the user in reducing the load on the primary database during working hours, but it may not necessarily help with the latency issue caused by the Multi-AZ feature.
Therefore, the answer is that all options may help the user to some extent, but none of them may completely solve the latency issue caused by the Multi-AZ feature. The user may need to investigate further to identify the root cause of the latency and take appropriate actions to address it.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question403:"link"


