---
layout: default 
title: "917 - A company has a set of web servers
It is"
link: "https://www.exam-answer.com/amazon/SAA-C03/question134"
---


[.question]
== 917-64a1fa65f053625db51dde77.


****

[.query]
--

Your system has been under attack, and you've decided that all access logs and other log files generated by your web servers and applications servers need to be consumed and analysed in realtime.

How would you configure your AWS environment to support zero-data-loss log file ingestion and realtime data analytics that attempt to identify illegal access attempts?


--

[.list]
--
* [ ] A. Send the log files to CloudTrail and have the security team look for anomolies
* [ ] B. Use Amazon SQL for zero-data-loss log ingestion and Amazon Kinesis for analytics
* [ ] C. Use Amazon Kinesis for log ingestion and for realtime analytics processing
* [ ] D. Stream logs to SQS and analyze them with Python apps that perform data analytics

--
****

[.answer]
Correct Answer  C

[.explanation]
--

For realtime ingestion of data and concurrent analytics processing, Amazon Kinesis is the right tool.

AWS CloudTrail is great for logging and auditing of actions performed on your AWS account, but it's not to be used for ingesting streamed data or realtime analytics.

Kinesis and CloudTrail are two AWS services that serve different purposes:

Amazon Kinesis: Amazon Kinesis is a managed streaming data service that enables real-time processing of large amounts of data from multiple sources. It is designed for ingesting, processing, and analyzing streaming data such as website clickstreams, IoT sensor data, application logs, and more. Kinesis provides capabilities to collect, store, process, and analyze data in real-time, allowing you to build real-time streaming applications and gain insights from streaming data. It offers several services within the Kinesis family, including Kinesis Data Streams, Kinesis Data Firehose, and Kinesis Data Analytics.

AWS CloudTrail: AWS CloudTrail is a service that provides detailed logging and auditing of actions performed within your AWS account. It records and stores API calls made by or on behalf of your account, capturing details such as the identity of the caller, the time of the call, the actions performed, and more. CloudTrail logs can be used for various purposes, including security analysis, compliance auditing, troubleshooting, and resource change tracking. It helps you gain visibility into the activity happening within your AWS infrastructure.

The big difference between Kinesis and CloudTrail is their primary purpose. Kinesis is focused on real-time streaming data processing and analysis, while CloudTrail is focused on providing audit trails and logs for monitoring and auditing AWS API activities. If you need to process and analyze real-time streaming data, Kinesis is the appropriate choice. If you require detailed audit trails and monitoring of API activity within your AWS account, CloudTrail is the suitable option.

--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question134:"link"


