---
layout: default 
title: "1196 - Your company currently has the following"
---


[.question]
== 1196-64a1fae2f053625db51ddfc0.


****

[.query]
--
Your company currently has the following architecture for its e-commerce application. · EC2 Instances hosting the application · An Autoscaling group for the EC2 Instances The users who use the application keep on complaining that the application is slow in the morning from 9:00 - 9:30, after which no issues occur.
Which of the following can be done to ensure the issue is not encountered during the morning time?


--

[.list]
--
* [*] A. Ensure that a Simple scaling policy is added to the Auto scaling Group.
* [ ] B. Ensure that a step scaling policy is added to the Auto scaling Group.
* [*] C. Ensure that a scheduled scaling policy is added to the Auto scaling Group.
* [ ] D. Ensure that a static scaling policy is added to the Auto scaling Group.

--
****

[.answer]
Answer  C

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - C.
The AWS Documentation mentions the following.
Scaling based on a schedule allows you to scale your application in response to predictable load changes.
For example, every week, the traffic to your web application starts to increase on Wednesday, remains high on Thursday, and starts to decrease on Friday.
You can plan your scaling activities based on the predictable traffic patterns of your web application.
Option A is incorrect because simple scaling increases or decreases the group's current capacity based on a single scaling adjustment.
Option B is incorrect because Step Scaling increases or decreases the group's current capacity based on a set of scaling adjustments, known as step adjustments, that vary based on the size of the alarm breach.
Option D is incorrect since Static scaling policy doesn't exist.
For more information on scaling policies for Auto scaling, please refer to the below URL's-
https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scale-based-on-demand.html#as-scaling-types https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-simple-step.html
The issue of slow application performance during specific times suggests that there is a sudden increase in traffic to the application during that period. The current architecture, which uses an EC2 Autoscaling group, can help with handling increases in traffic, but it may not be configured properly to handle such sudden surges.
A. Adding a Simple scaling policy to the Autoscaling group means that the group will automatically adjust the number of instances based on CPU utilization or any other metric that is specified. This policy may not be effective in handling sudden surges of traffic since it may take time to spin up new instances, and this could cause the application to continue to be slow during the morning period.
B. A step scaling policy would allow the Autoscaling group to adjust the number of instances based on the metric in a predefined set of steps, which would be faster than a simple scaling policy. This policy may be helpful, but it may not be ideal if the surge in traffic is not predictable or if the number of instances required during the surge varies widely.
C. A scheduled scaling policy allows the Autoscaling group to adjust the number of instances based on a predetermined schedule. This policy may be ideal for addressing the morning slowdown issue since it allows for preemptive scaling before the expected surge in traffic. By adding a scheduled scaling policy to the Autoscaling group, it is possible to have the group automatically spin up additional instances before the morning period, ensuring that there are enough resources available to handle the surge in traffic.
D. A static scaling policy means that the number of instances in the Autoscaling group is fixed, and it does not change based on any metric or schedule. This policy may not be effective in handling the morning slowdown issue since it does not allow for additional resources to be added during the expected surge in traffic.
Therefore, the best option for ensuring that the issue is not encountered during the morning period is to add a scheduled scaling policy to the Autoscaling group (Option C).
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question466:"link"


