---
layout: default 
title: "871 - Your team is developing a highperformanc"
---


[.question]
== 871-64a1fa54f053625db51dde42.


****

[.query]
--
Your team is developing a high-performance computing (HPC) application.
The application resolves complex, compute-intensive problems and needs a high-performance and low-latency Lustre file system.
You need to configure this file system in AWS at a low cost.
Which method is the most suitable?


--

[.list]
--
* [*] A. Create a Lustre file system through Amazon FSx.
* [ ] B. Launch a high performance Lustre file system in Amazon EBS.
* [*] C. Create a high-speed volume cluster in EC2 placement group.
* [ ] D. Launch the Lustre file system from AWS Marketplace.

--
****

[.answer]
Correct Answer  A

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - A.
The Lustre file system is an open-source, parallel file system that can be used for HPC applications.
Refer to http://lustre.org/ for its introduction.
In Amazon FSx, users can quickly launch a Lustre file system at a low cost.
Option A is CORRECT: Amazon FSx supports Lustre file systems, and users pay for only the resources they use.
Option B is incorrect: Although users may be able to configure a Lustre file system through EBS, it needs lots of extra configurations.
Option A is more straightforward.
Option C is incorrect: Because the EC2 placement group does not support a Lustre file system.
Option D is incorrect: Because products in AWS Marketplace are not cost-effective.
For Amazon FSx, there are no minimum fees or set-up charges.
Check its pricing in.
https://aws.amazon.com/fsx/lustre/pricing/.
Option A is the most suitable method to configure a high-performance Lustre file system in AWS at a low cost.
Amazon FSx is a fully-managed service that makes it easy to create and run Lustre file systems that are optimized for HPC workloads. With Amazon FSx, users can launch and scale Lustre file systems quickly and easily, without having to manage the underlying infrastructure.
Option B, launching a high-performance Lustre file system in Amazon EBS, is not an appropriate method because Amazon EBS is designed for block storage, not file storage, and it is not optimized for HPC workloads.
Option C, creating a high-speed volume cluster in an EC2 placement group, is not an appropriate method for configuring a Lustre file system because it does not provide a file system solution that can be used by multiple EC2 instances simultaneously.
Option D, launching the Lustre file system from AWS Marketplace, is not an appropriate method because AWS Marketplace is a platform for buying and selling software, not for configuring file systems.
Therefore, option A is the most suitable method for configuring a high-performance Lustre file system in AWS at a low cost.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question81:"link"


