---
layout: default 
title: "1336 - You are working as an AWS architect in y"
link: "https://www.exam-answer.com/amazon/SAA-C03/question655"
---


[.question]
== 1336-64a1fb2ff053625db51de07c.


****

[.query]
--
You are working as an AWS architect in your organization.
An application is being developed on an AWS EC2 instance and would need a local volume with low latency to handle database workloads.
They figured out the Provisioned IOPS SSD volume type suits best.
However, when the application team is launching an EC2 instance, they found an option named “EBS-optimized.” They reached out to you asking the purpose of EBS optimized instances.
What do you suggest?


--

[.list]
--
* [*] A. Amazon EBS–optimized instance provides additional, dedicated capacity for Amazon EBS I/O.
* [ ] B. Amazon EBS-optimized instance comes with instance store ephemeral storage which provides faster throughput.
* [ ] C. EBS-optimized is a configuration on the EBS volume, not an option on EC2 instance.
* [ ] D. Amazon EBS-optimized instances cannot have Provisioned IOPS SSD volume types. They only work with General Purpose SSD, Throughput optimized HDD, Cold HDD.

--
****

[.answer]
Answer A

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer: A.
An Amazon EBS-optimized instance uses an optimized configuration stack and provides additional, dedicated capacity for Amazon EBS I/O.
This optimization provides the best performance for your EBS volumes by minimizing contention between Amazon EBS I/O and other traffic from your instance.
EBS-optimized instances deliver dedicated bandwidth to Amazon EBS, with options between 425 Mbps and 14,000 Mbps, depending on the instance type you use.
When attached to an EBS-optimized instance, General Purpose SSD (gp2) volumes are designed to deliver within 10% of their baseline and burst performance 99% of the time in a given year.
Provisioned IOPS SSD (io1) volumes are designed to deliver within 10% of their provisioned performance 99.9% of the time in a given year.
Both Throughput Optimized HDD (st1) and Cold HDD (sc1) guarantee performance consistency of 90% of burst throughput 99% of the time in a given year.
Non- compliant periods are approximately uniformly distributed, targeting 99% of the expected total throughput each hour.
For more information on EBS-optimized instances, refer to the documentation here.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html
Sure, I'd be happy to help!
When launching an EC2 instance, you may notice an option called "EBS-optimized" in the configuration. This option is related to the performance of Elastic Block Store (EBS) volumes attached to your EC2 instance.
EBS is a service that provides block-level storage volumes for use with EC2 instances. EBS volumes can be attached to EC2 instances and can be used like a physical hard drive. EBS volumes can be either General Purpose SSD, Provisioned IOPS SSD, Throughput Optimized HDD, or Cold HDD, depending on your specific requirements.
The "EBS-optimized" option in EC2 configuration provides additional, dedicated capacity for EBS I/O. This means that the EC2 instance is optimized to handle EBS volumes and their workloads. This optimization is achieved through the use of additional network capacity dedicated to EBS I/O.
By selecting the "EBS-optimized" option, you can improve the performance of your EBS volumes and reduce the impact of contention with other network traffic. This option is particularly useful if your application has high I/O demands or requires low latency access to EBS volumes.
However, it's worth noting that selecting the "EBS-optimized" option does not affect the type of EBS volume you can use. You can still choose between General Purpose SSD, Provisioned IOPS SSD, Throughput Optimized HDD, or Cold HDD volumes based on your specific requirements.
In summary, the correct answer is A: Amazon EBS-optimized instance provides additional, dedicated capacity for Amazon EBS I/O.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question655:"link"


