---
layout: default 
title: "902 - You have an EC2 instance in the AWS usea"
link: "https://www.exam-answer.com/amazon/SAA-C03/question117"
---


[.question]
== 902-64a1fa5ff053625db51dde66.


****

[.query]
--
You have an EC2 instance in the AWS us-east-1 region.
The application in the instance needs to access a DynamoDB table that is located in the AWS us-east-2 region.
The connection must be private without leaving the Amazon network.
The instance should not use any public IP for communication.
How would you configure this?


--

[.list]
--
* [*] A. Configure an inter-region VPC endpoint for the DynamoDB service.
* [*] B. Configure inter-region VPC peering and create a VPC endpoint for DynamoDB in us-east-1.
* [ ] C. Create an inter-region VPC peering connection between us-east-1 and us-east-2.
* [ ] D. There is no way to setup the private inter-region connections.

--
****

[.answer]
Answer  B

[.explanation]
--
To configure a private connection between an EC2 instance in the us-east-1 region and a DynamoDB table in the us-east-2 region, without using any public IP for communication, you can follow these steps:

Create a VPC Peering Connection: In the AWS Management Console, create a VPC peering connection between the VPC in the us-east-1 region where the EC2 instance is located and the VPC in the us-east-2 region where the DynamoDB table resides. This establishes a private network connection between the two VPCs.

Update Route Tables: Modify the route tables in both VPCs to allow traffic between the subnets associated with the EC2 instance and the DynamoDB table. Add a route in the route table of the us-east-1 VPC pointing to the VPC peering connection for the us-east-2 VPC, and vice versa. This ensures that the traffic destined for the DynamoDB table is routed through the peering connection.

Security Group Configuration: Adjust the security groups associated with the EC2 instance and the DynamoDB table to allow inbound and outbound traffic between them. Update the security group rules to permit the necessary protocols (such as TCP) and ports for communication.

VPC Endpoint for DynamoDB: Create a VPC endpoint for DynamoDB in the us-east-1 VPC. This allows the EC2 instance to directly access the DynamoDB service without needing to go over the public internet. Configure the VPC endpoint to route the traffic to the us-east-2 region where the DynamoDB table is located.

Update Application Configuration: Modify the application running on the EC2 instance to use the appropriate endpoint or endpoint URL for accessing the DynamoDB table. This ensures that the application connects to the DynamoDB service using the private VPC endpoint.

By following these steps, you can establish a private and secure connection between the EC2 instance in the us-east-1 region and the DynamoDB table in the us-east-2 region, without relying on public IPs for communication. The VPC peering connection, route table updates, security group configuration, and VPC endpoint setup enable the private network connectivity required for accessing the DynamoDB table from the EC2 instance.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question117:"link"


