---
layout: default 
title: "839 - One of your colleagues who is new to the"
---


[.question]
== 839-64a1fa48f053625db51dde1b.


****

[.query]
--
One of your colleagues, who is new to the company where you work as a cloud Architect, has some issues with IP Addresses.
He has created an Amazon VPC with an IPV4 CIDR block 10.0.0.0/24, but now there is a requirement of hosting a few more resources to that VPC.
As per his knowledge, he is thinking of creating a new VPC with a greater range.
Could you suggest to him a better way that should be reliable?


--

[.list]
--
* [*] A. Delete the existing subnets in the VPC and create new Subnets in VP.
* [ ] B. He is thinking of the right approach.
* [*] C. You can create new VPC and connect old VPC with a new one.
* [*] D. You can expand existing VPC by adding Secondary CIDR to your current VP.

--
****

[.answer]
Correct Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - D.
Options A, B, C are incorrect because it is not reliable to go for this type of approach as VPC to VPC connection will take new resources like VPC Peering.
Creating a new VPC or Subnet is also not suggested.
Option D is correct because you can associate Secondary CIDR to your current VPC to accommodate more hosts.
Refer: https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html#add-ipv4-cidr.
The best option for hosting additional resources in an Amazon VPC with an IPV4 CIDR block 10.0.0.0/24 is to expand the existing VPC by adding Secondary CIDR to the current VPC.
Expanding the VPC by adding Secondary CIDR to the current VPC is a reliable and straightforward solution for this scenario. With Secondary CIDR, you can extend the CIDR block range of your existing VPC without having to create a new VPC. This will enable you to add more resources to the existing VPC without the need to reconfigure the network settings.
By using Secondary CIDR blocks, you can have multiple IP address ranges in your VPC. Each of these CIDR blocks is associated with a subnet, allowing you to create multiple subnets with different IP address ranges within the same VPC.
To add a Secondary CIDR block to your VPC, follow these steps:
1.
Open the Amazon VPC console.
2.
In the navigation pane, choose "Your VPCs."
3.
Select the VPC for which you want to add a Secondary CIDR block.
4.
Choose the "CIDR blocks" tab, and then choose "Edit CIDRs."
5.
In the "Add CIDR" dialog box, enter the new CIDR block range that you want to add.
6.
Choose "Save."
Once you add a Secondary CIDR block, you can create new subnets within the range of that block. You can also modify existing subnets to use the new CIDR block range.
In conclusion, adding a Secondary CIDR block to your current VPC is the recommended solution for expanding your VPC's IP address range and hosting additional resources in your VPC without having to create a new VPC.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question42:"link"


