---
layout: default 
title: "922 - A company has an application that stores"
link: "https://www.exam-answer.com/amazon/SAA-C03/question139"
---


[.question]
== 922-64a1fa66f053625db51dde7c.


****

[.query]
--

Your client has a massive number of thumbnail images for old movies that are almost never queried.

The images must be available immediately if a query for any of these frequently viewed movies are requested, but the likelihood of any of these movies thumbnails being accessed throughout the year is very low.

What is the best storage option for these thumbnail images?


--

[.list]
--
* [ ] A. Amazon S3 Standard.
* [ ] B. Amazon Elastic File System.
* [ ] C. Amazon S3 Standard Infrequent Access.
* [ ] D. Amazon Glacier with Expedited Retrievals.

--
****

[.answer]

C



[.explanation]
--

Amazon S3 Standard Infrequent Access is a perfect fit for this use case.

S3 standard would cost more money with no discernable benefit.

Amazon Glacier does not provide immediate retrieval. On Glacier, retrieval will be minutes or hours.

Amazon EFS is not for object storage but instead for files that will be concurrently accessed. It's not a good fit here.

Amazon S3 Standard Infrequent Access is the cheapest and best solution for this scenario.
--

[.ka]
DCO

'''



https://www.exam-answer.com/amazon/SAA-C03/question139:"link"


