---
layout: default 
title: "1209 - A company is planning to host an activea"
---


[.question]
== 1209-64a1fae9f053625db51ddfd0.


****

[.query]
--
A company is planning to host an active-active site.
One site will be deployed in AWS, and the other one on their On-premise data center.
They need to ensure that the traffic is distributed to multiple resources, proportionately between both sites.
Which of the following routing policy would you use for this purpose?


--

[.list]
--
* [*] A. Simple Routing
* [ ] B. Failover Routing
* [ ] C. Latency Routing
* [*] D. Weighted Routing.

--
****

[.answer]
Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - D.
The AWS Documentation mentions the following.
Weighted routing lets you associate multiple resources with a single domain name (example.com) or subdomain name (acme.example.com) and choose how much traffic is routed to each resource.
This can be useful for various purposes, including load balancing and testing new versions of software.
To configure weighted routing, you create records with the same name and type for each of your resources.
You assign each record a relative weight that corresponds with how much traffic you want to send to each resource.
Amazon Route 53 sends traffic to a resource based on the weight you assign to the record as a proportion of the total weight for all the group records.
Option A is incorrect since this should be used when you want to configure standard DNS records.
Option B is incorrect since this should be used when you want to route traffic to a resource when the resource is healthy or to a different resource when the first resource is unhealthy.
Option C is incorrect since this should be used when you want to improve your users' performance by serving their requests from the AWS Region that provides the lowest latency.
For more information on a Routing policy, please refer to the below URL-
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html
For the scenario of hosting an active-active site with one site deployed in AWS and the other on-premise data center, the routing policy that should be used to ensure that traffic is distributed to multiple resources proportionately between both sites is Weighted Routing.
Weighted Routing policy is a type of Amazon Route 53 routing policy that enables traffic distribution across multiple resources based on assigned weights. The assigned weights can be used to allocate the percentage of traffic that should be sent to each resource. This is achieved by creating weighted resource record sets for each resource, where the weight assigned to each record set determines the proportion of traffic that it should receive.
In this case, one weighted resource record set should be created for the AWS site and another for the on-premise data center. The weights assigned to each record set should be based on the capacity and performance of the resources at each site. For example, if the AWS site has more resources than the on-premise data center, a higher weight can be assigned to the AWS record set to ensure that it can handle more traffic.
By using Weighted Routing policy, traffic can be distributed proportionately between both sites, ensuring that both sites are active and receiving traffic at all times. In addition, the weights assigned to each resource record set can be adjusted as needed to accommodate changes in resource capacity or performance.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question482:"link"


