---
layout: default 
title: "801 - Your company is planning on the followin"
link: "https://www.exam-answer.com/amazon/SAA-C03/question1"
---

[.link]
http://www.ibm.com

[.question]
== 801-64a1fa3bf053625db51dddf3.


****

[.query]
--
Your company is planning on the following architecture for their application. A set of EC2 Instances hosting the web part of the application. A relational database for the backend. A Load balancer for distribution of traffic. A NAT gateway for routing traffic from the database server to the Internet. Which of the following architecture ensures high availability across all components?


--

[.list]
--
* [ ] A. A Load balancer with one public subnet, one private subnet. The EC2 Instances placed in one Availability Zone. RDS with Multi-AZ Enabled. NAT Gateway in one availability zone.
* [*] B. A Load balancer with 2 public subnets, 2 private subnets. The EC2 Instances placed across 2 Availability Zones. RDS with Multi-AZ Enabled. NAT Gateways in each availability zone.
* [ ] C. A Load balancer with 2 public subnets, 2 private subnets. The EC2 Instances placed in 2 Availability Zones. RDS with Multi-AZ Enabled. NAT Gateway in one availability zone.
* [ ] D. A Load balancer with 2 public subnets, 2 private subnets. The EC2 Instances placed in one Availability Zone. RDS with Multi-AZ Enabled. NAT Gateway in one availability zone.

--
****

[.answer]
Answer B

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer: B.

Option B provides the best architecture that balances availability and securing by incorporating the following elements:

A Load Balancer: By using a load balancer, traffic is distributed across multiple EC2 instances, allowing for better scalability and fault tolerance.

Public and Private Subnets: The use of public and private subnets ensures a separation of traffic and provides additional security. The web instances can reside in the public subnets accessible from the internet, while the database can be placed in private subnets for added protection.

EC2 Instances across Availability Zones: Placing the EC2 instances across multiple Availability Zones ensures that if one zone experiences an outage, the application can still be accessed from the other zone, providing high availability.

RDS with Multi-AZ Enabled: Enabling Multi-AZ for the RDS database ensures that a synchronous replica is created in another Availability Zone. In the event of a failure in the primary zone, automatic failover occurs to the standby replica, minimizing downtime and maintaining data availability.

NAT Gateways: By having NAT Gateways in each availability zone, the database server can route traffic to the internet securely, ensuring connectivity and access to external resources.

This architecture design combines load balancing, redundancy, and fault tolerance mechanisms to achieve high availability across all components, making it the most suitable answer.


--

[.ka]
null

'''





