---
layout: default 
title: "810 - Your company is planning to use Route 53"
link: "https://www.exam-answer.com/amazon/SAA-C03/question11"
---


[.question]
== 810-64a1fa3ef053625db51dddfd.


****

[.query]
--
Your company is planning to use Route 53 as the DNS provider.
There is a need to ensure that the company's domain name points to an existing CloudFront distribution.
How could this be achieved?


--

[.list]
--
* [*] A. Create an Alias record which points to the CloudFront distribution.
* [ ] B. Create a host record which points to the CloudFront distribution.
* [*] C. Create a CNAME record which points to the CloudFront distribution.
* [ ] D. Create a Non-Alias Record which points to the CloudFront distribution.

--
****

[.answer]
Correct Answer  A

[.explanation]
--
The correct option is to create an alias record. Here's how to do it:

Create a hosted zone in Route 53: Firstly, you would create a hosted zone in Route 53 for the company's domain name. This allows Route 53 to manage the DNS records for that domain.

Create an "Alias" record: In the hosted zone, you would create an "Alias" record that maps the domain name to the CloudFront distribution. This record type is used to associate the domain name directly with the CloudFront distribution without using an intermediate CNAME record.

Select the CloudFront distribution: When creating the "Alias" record, you would select the CloudFront distribution as the target. This ensures that requests for the domain name are routed to the CloudFront distribution.

Update the domain's DNS settings: Finally, you would update the DNS settings for the domain with the assigned name servers provided by Route 53. This change allows Route 53 to handle DNS resolution for the domain.

How it works:

When a user enters the company's domain name in their web browser, their DNS resolver queries the authoritative name servers specified in the domain's DNS settings (updated in step 4).

Since Route 53 is now the DNS provider for the domain, it receives the DNS query. Route 53 then looks up the "Alias" record created in step 2, which points to the CloudFront distribution.

Route 53 responds to the DNS resolver with the IP address of the CloudFront distribution. The DNS resolver then routes the user's request to the CloudFront distribution's IP address.

CloudFront acts as a content delivery network (CDN) and caches content from origin servers. It receives the user's request and retrieves the corresponding content from the configured origin server, such as an S3 bucket or an EC2 instance.

CloudFront delivers the requested content back to the user, ensuring faster and more efficient content delivery due to its global edge locations.

In summary, by creating an "Alias" record in Route 53 that points to the CloudFront distribution, and updating the domain's DNS settings to use Route 53's name servers, the company's domain name will effectively direct traffic to the associated CloudFront distribution. This setup enables efficient content delivery and enhances the overall performance and availability of the company's web application or website.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question11:"link"


