---
layout: default 
title: "923 - A security audit discovers that one of y"
link: "https://www.exam-answer.com/amazon/SAA-C03/question140"
---


[.question]
== 923-64a1fa66f053625db51dde7d.


****

[.query]
--

A client says their RDS database is unencrypted which puts it in violation of compliance rules.

What advice do you give to your client with regards to encrypting an unencrpyted RDS database?


--

[.list]
--
* [ ] A. Simply turn on the RDS option to encrypt data at rest and the database will be encrypted.
* [ ] B. Have the client create and RDS snapshop. Then copy the snapshot with encryption enabled. Then restore the encrypted snapshop.
* [ ] C. RDS databases cannot be encrypted
* [ ] D. All RDS databases are encyrpted so there is no non-compliance issue

--
****

[.answer]
B

[.explanation]
--
Encrypting an unencrypted RDS database is a multi-step process. It's not as simple as flicking a switch.

A snapshot must be taken, the RDS console must be copied with encryption enagled, and then the encrypted snapshot must be restored.

It's ugly, but it works.

--

[.ka]
null

'''

