---
layout: default 
title: "811 - You are building an automated transcript"
link: "https://www.exam-answer.com/amazon/SAA-C03/question12"
keywords: S3
---


[.question]
== 811-64a1fa3ff053625db51dddfe.


****

[.query]
--

You are building a new application that stores large video files along with a transcription of the audio contained in the video file.

The transcripts, which are in JSON format, are accessed regularly by various EC2 instances that perform data analysis on the text.

This is a new application you are building and the future capacity requirements are unknown.

What is the simplest and most cost effective solution to use as you initially architect this solution?



--

[.list]
--
* [*] A. Just use an Amazon S3 bucket
* [ ] B. Configure each EC2 server with an instance store
* [*] C. Amazon EBS volumes will be the cheapest
* [ ] D. This is the prototypical use-case for Amazon Glacier

--
****

[.answer]
Correct Answer  C

[.explanation]
--

This is the perfecte use-case for Amazon S3.

S3 is simple, it is cheaper than an EBS volume and it can scale seamlessly when more capacity is required.

--

[.ka]
DCO

'''



https://www.exam-answer.com/amazon/SAA-C03/question12:"link"


