---
layout: default 
title: "921 - Thirdparty signin Federation has been im"
link: "https://www.exam-answer.com/amazon/SAA-C03/question138"
keywords: S3, federated, login, authorization, authentication
---


[.question]
== 921-64a1fa66f053625db51dde7b.


****

[.query]
--

To simplify access to your website, you use Facebook and Twitter for federated login and authentication.

However, since Sunday users have reported an inability to access images that are pulled from S3 buckets.

What is the most likely cause of this unforseen disruption in service?

--

[.list]
--
* [ ] A. IAM group policies were updated making S3 bucket access more restricted
* [ ] B. IAM resource policies for the S3 bucket were changed to something more restrictive
* [ ] C. The federated login authorization protocols are being blocked by a firewall.
* [ ] D. The federated login providers have moved to a newer version of OAUTH

--
****

[.answer]
B

[.explanation]
--

This wouldn't be caused by IAM group policies. Group policies deal with authorization for IAM users  in AWS to AWS resources. IAM groups are not directly tied to federated logins.

The federated login deals with authorization, that is proving who you are, not authorization, so the idea of authorization protocols being blocked makes no sense.

Similarly, OUATH has nothing to do with accessing AWS resources after authentication has occurred, so this is incorrect.

The best option here is that someone changed the S3 bucket policy to something more restrictive. If you all of a sudden set a deny-all policy on an S3 bucket, nobody is going to be able to access it, regardless of how they authenticated into AWS.


--

[.ka]
DSA

'''



https://www.exam-answer.com/amazon/SAA-C03/question138:"link"


