---
layout: default 
title: "1074 - You are requested to guide a large Pharm"
---


[.question]
== 1074-64a1faa4f053625db51ddf27.


****

[.query]
--
You are requested to guide a large Pharma company.
They are looking for a solution to save all their R&D test analysis data securely.
Daily large numbers of reports are generated; this data would be accessed parallel from multiple R&D centers spread across the globe.
The company requires this data to be instantaneously available to all users.
Which of the following is the most suitable way for AWS storage to provide low latency access to users across the globe with the least cost?


--

[.list]
--
* [*] A. Use Amazon EC2 instance with instance store to store data.
* [ ] B. Use Amazon EFS volumes to store data.
* [*] C. Use Amazon EBS volumes connected to the EC2 instance to store data
* [*] D. Use Amazon S3 Buckets to store data.

--
****

[.answer]
Correct Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - D.
Amazon S3 can be used to store any amount of data that can be accessed from multiple locations concurrently without any impact on latency.
Option A is incorrect as the Instance store will provide low latency access from EC2 instances, but it's a temporary storage option.
Option B is incorrect.
Since this data would be accessed globally, Amazon EFS will not be ideal for this requirement.
Option C is incorrect as Amazon EBS volumes would be useful storage for single Amazon EC2 instances.
For more information on AWS Storage options, refer to the following URLs-
https://d0.awsstatic.com/whitepapers/AWS%20Storage%20Services%20Whitepaper-v9.pdf
The most suitable option for storing and accessing data in a low-latency and cost-effective manner for a large Pharma company would be to use Amazon S3 buckets. Here's why:
A. Using Amazon EC2 instances with instance store to store data would be a bad choice as instance store volumes are temporary, local storage, and not durable. They are also not accessible from other EC2 instances or from outside the instance, which means that the data would be lost if the instance is stopped or terminated. Also, the data would not be accessible to all users globally due to the limited availability of the instance.
B. Using Amazon EFS volumes to store data would be an option, but it may not be the most cost-effective solution for this use case. EFS is a shared, elastic file storage system that can be accessed by multiple EC2 instances and is designed for scalable, highly available, and durable storage. However, it can be more expensive than S3 and can incur additional charges for data transfer, metadata operations, and accessing files from different regions.
C. Using Amazon EBS volumes connected to the EC2 instance to store data is similar to using EC2 instances with instance store, as it only provides local storage for the EC2 instance. This solution may not be suitable for storing large volumes of data or providing low-latency access to users across the globe.
D. Using Amazon S3 buckets to store data is the best solution for this use case. S3 is a highly scalable, durable, and secure object storage service designed for storing and retrieving any amount of data from anywhere in the world. S3 provides low-latency access to data and can be accessed through a simple API or web interface. S3 also provides versioning, lifecycle policies, cross-region replication, and security features to ensure data protection and compliance.
In conclusion, the most suitable option for this Pharma company would be to use Amazon S3 buckets to store their R&D test analysis data securely and provide low-latency access to users across the globe at a low cost.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question313:"link"


