---
layout: default 
title: "910 - You have a web application hosted on an "
link: "https://www.exam-answer.com/amazon/SAA-C03/question127"
---


[.question]
== 910-64a1fa62f053625db51dde70.


****

[.query]
--
Global users of you web application hosted on a single, T2 EC2 instance in Montreal are peeved over how slow it is.

What's the first architectural change you'd make to improve global response times for people accessing your website?


--

[.list]
--
* [ ] A. Upgrade from T2 to a T3 EC2 instance.
* [ ] B. Re-architect you web application to use AWS Lambda.
* [ ] C. Incorporate AWS CloudFront into your architecutre.
* [ ] D. Use health checks and autoscale when response times are low

--
****

[.answer]
Correct Answer C

[.explanation]
--
The simplest way to improve global response times, especially for web applications hostes on a single EC2 instance that is not in close proximity to all your clients, is to use CloudFront.

AWS CloudFront is a content delivery network (CDN) service provided by Amazon Web Services. It helps web applications improve response times and enhance the user experience for users accessing the application from various locations around the globe by doing the following things:

Content Caching: CloudFront caches static and dynamic content at edge locations worldwide. When a user requests content from your web application, CloudFront delivers the content from the nearest edge location instead of retrieving it from the origin server. This reduces latency and improves response times since the content is delivered from a location closer to the user.

Global Edge Network: CloudFront has a vast network of edge locations spread across different geographical regions. These edge locations are strategically placed to bring the content closer to end-users, reducing the distance the data needs to travel. By leveraging the global edge network, CloudFront can serve content with lower latency, resulting in faster response times.

Reduced Network Congestion: CloudFront helps alleviate network congestion by offloading traffic from the origin server to the edge locations. When a user requests content, CloudFront caches and serves it from the edge location closest to the user. This reduces the load on the origin server and improves overall performance, especially during high-traffic periods.

Intelligent Content Delivery: CloudFront uses various techniques to optimize content delivery. It automatically determines the most efficient route to deliver content based on network conditions, taking into account factors like network latency, packet loss, and congestion. This intelligent routing ensures that users receive content through the fastest and most reliable path, further improving response times.

Dynamic Content Acceleration: CloudFront supports dynamic content acceleration by caching and delivering dynamic content more efficiently. It can cache dynamic content at the edge locations for a specified period, reducing the need to fetch the content from the origin server for every user request. This significantly improves response times for dynamic web applications.

Customization and Integration: CloudFront integrates seamlessly with other AWS services, allowing you to customize and enhance its functionality. You can use features like Lambda@Edge to run serverless code at the edge locations, enabling you to further optimize content delivery and tailor the user experience based on specific requirements.

By leveraging these capabilities, AWS CloudFront helps web applications accessed throughout the globe improve response times, reduce latency, and deliver content more efficiently. It brings the content closer to users, offloads traffic from the origin server, and utilizes a global network of edge locations to ensure fast and reliable content delivery, resulting in an improved user experience.



--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question127:"link"


