---
layout: default 
title: "909 - You have designed an application that us"
link: "https://www.exam-answer.com/amazon/SAA-C03/question126"
---


[.question]
== 909-64a1fa62f053625db51dde6f.


****

[.query]
--

Your secure, online application uses S3, Kubernetes, EC2 instances and even an RDS database.

You want who users to sign in through a federated identiy provider such as Google, Facebook and Instagram accounts so it's easier for them to register and access your site.

However, you also want to use AWS Cognito for authorization. How can this be configured?


--

[.list]
--
* [ ] A. Authorize access to resources through a Cognito identity pool.
* [ ] B. AWS Cognito cannot be integrated with 3rd party federated identity providers like Facebook and Instagram.
* [ ] C. Use a federated identity provider to authenticate into a Cognito identity pool.
* [ ] D. Configure your web server to support OAUTH and allow OAUTH to authenticate and authorize.

--
****

[.answer]
Correct Answer  AC

[.explanation]
--

A great way to simplify the registration and login process in AWS is to use a federated identity provider like Facebook or Google for authentication, and then after authentication, add users to a Cognito identity pool for resource authorization.

With Cognito identity pools, users can sign in using various authentication methods, including username and password, as well as social identity providers like Google, Facebook, or Amazon. Cognito identity pools act as a unified identity provider, allowing your application to support multiple authentication methods and granting temporary, limited-privilege AWS credentials to users.

By integrating with federated identity providers, you enable users to sign in to your application using their Google, Facebook, or other supported accounts, without the need to create separate credentials for your application. This can simplify the sign-up process and increase user convenience, as they can use their existing social media or other online account credentials to access your application.

Cognito identity pools provide a comprehensive solution for managing user identities and access control within your application, while federated identity providers offer a convenient way for users to authenticate using their existing credentials from external identity providers. By combining the two, you can enhance the usage and ease of signing up for your application by providing users with multiple authentication options and allowing them to leverage their preferred identity provider.


--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question126:"link"


