---
layout: default 
title: "903 - An EC2 Instance hosts a Javabased applic"
link: "https://www.exam-answer.com/amazon/SAA-C03/question119"
---


[.question]
== 903-64a1fa60f053625db51dde68.


****

[.query]
--
An EC2 Instance hosts a Java-based application that accesses a DynamoDB table.
This EC2 Instance is currently serving production users.
What would be a secure way for the EC2 Instance to access the DynamoDB table?


--

[.list]
--
* [*] A. Use IAM Roles with permissions to interact with DynamoDB and assign it to the EC2 Instance.
* [ ] B. Use KMS Keys with the right permissions to interact with DynamoDB and assign it to the EC2 Instance.
* [ ] C. Use IAM Access Keys with the right permissions to interact with DynamoDB and assign it to the EC2 Instance.
* [ ] D. Use IAM Access Groups with the right permissions to interact with DynamoDB and assign it to the EC2 Instance.

--
****

[.answer]
A

[.explanation]
--
A secure way for the EC2 Instance to access the DynamoDB table would be to use IAM roles in AWS.

Here's how you can configure it:

Create an IAM role: Create an IAM role with the necessary permissions to access the DynamoDB table. Include the required read or write access permissions for the table in the role's IAM policy.

Attach the IAM role to the EC2 Instance: Once the IAM role is created, attach it to the EC2 Instance. You can do this during instance launch or by modifying the instance's IAM role later.

Update the Java application configuration: Within the Java application running on the EC2 Instance, configure the AWS SDK to use the IAM role assigned to the instance. The SDK will automatically obtain temporary security credentials from the EC2 Instance metadata service when making requests to DynamoDB.

By using IAM roles, you eliminate the need to store access keys or credentials within the EC2 Instance. The temporary security credentials obtained by the instance are automatically rotated and managed by AWS. This approach ensures a secure and seamless way for the EC2 Instance to access the DynamoDB table without exposing any long-term access keys or secrets.

Additionally, you can further enhance the security by applying least privilege principles in the IAM policies. Only grant the necessary permissions required for the Java application to perform its intended operations on the DynamoDB table, reducing the risk of potential unauthorized access or unintended actions.

Remember to regularly review and update the IAM policies as per your application's requirements to maintain the principle of least privilege and ensure secure access to the DynamoDB table.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question119:"link"


