---
layout: default 
title: "900 - Your company currently has a set of nonp"
link: "https://www.exam-answer.com/amazon/SAA-C03/question114"
---


[.question]
== 900-64a1fa5ff053625db51dde63.


****

[.query]
--
Your company currently has a set of non-production EC2 Instances hosted in AWS.
To save costs, you want to stop the EC2 instance when the average CPU utilization percentage has been lower than 10 percent for 24 hours, signaling that it is idle and no longer in use.
Which step could be helpful to fulfill this requirement?


--

[.list]
--
* [*] A. Use CloudWatch Logs to store the state change of the instances.
* [*] B. Create Amazon CloudWatch alarms that monitor the CPU utilization metric and stop the instances when the alarms are triggered.
* [*] C. Use SQS to monitor the metric and add the record to a DynamoDB table.
* [ ] D. Use AWS Lambda to monitor the metric and store the state in a DynamoDB table.

--
****

[.answer]
Correct Answer B

[.explanation]
--
To fulfill the requirement of stopping EC2 instances when the average CPU utilization percentage has been lower than 10 percent for 24 hours, the following step could be helpful:

Enable Amazon CloudWatch detailed monitoring for the EC2 instances and configure a CloudWatch alarm based on CPU utilization.

By enabling detailed monitoring, CloudWatch collects more granular CPU utilization metrics at a frequency of one minute. This allows for more accurate monitoring and evaluation of CPU usage.

To create a CloudWatch alarm based on CPU utilization, you can set a threshold of 10 percent and a duration of 24 hours. This means that if the average CPU utilization remains below 10 percent for 24 consecutive hours, the alarm will be triggered.

Once the alarm is triggered, you can configure an action to stop the EC2 instance(s). This action can be performed using an AWS Lambda function or an AWS Systems Manager Automation document.

Here is a step-by-step breakdown:

Enable detailed monitoring for the EC2 instances: Enable detailed monitoring for the instances you want to monitor closely. This can be done during instance launch or by modifying the instance settings.

Create a CloudWatch alarm: In the CloudWatch console, create a new alarm and select the metric for CPU utilization. Set the threshold to 10 percent and configure a duration of 24 hours for the evaluation period.

Configure the action: When creating the alarm, specify the action that should be taken when the alarm state is triggered. In this case, you would configure the action to stop the EC2 instance(s).

Verify and test: Ensure that the alarm is set up correctly by testing it with simulated scenarios or monitoring the CPU utilization over time. You can also set up notifications to receive alerts when the alarm state changes.

With this setup, if the average CPU utilization of the EC2 instance(s) remains below 10 percent for 24 hours, the CloudWatch alarm will be triggered and the configured action will be executed to stop the instance(s). This helps save costs by automatically stopping idle instances when they are no longer in use.

It's important to note that this approach assumes that stopping the EC2 instances won't affect any critical processes or services running on them. Careful consideration should be given to ensure that stopping the instances will not cause any negative impact on your application or workflows.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question114:"link"


