---
layout: default 
title: "908 - You have a local data center onpremise t"
link: "https://www.exam-answer.com/amazon/SAA-C03/question125"
---


[.question]
== 908-64a1fa62f053625db51dde6e.


****

[.query]
--
An on-prem video storage warehouse needs to transfer their catalog of audio and video files to AWS S3.

- The total amount of the files is about 42TB but definitely not more than 48TB.
- This is a one-time deal. The client will sell all their on-prem hardware when the move is complete.
- The client does not want to transfer the data across their very slow and unreliable network.

As an AWS certified solution architect, which solution would you recommend?


--

[.list]
--
* [ ] A. Use AWS peer connections to connect on-prem to the cloud
* [ ] B. Use a 50TB AWS Snowball device.
* [ ] C. Use an 80 TB Snowball Edge Storage Optimized device.
* [ ] D. Transfer the data to the cloud using AWS Direct Connect.
* [ ] E. Transfer the on-prem data to the cloud using a VPC

--
****

[.answer]
Correct Answer  C

[.explanation]
--
The correct answer is to use an 80 TB Snowball Edge Storage Optimized device. Note that the traditional, smaller Snowball devices are no longer available. Snowball Edge devices, with new 80TB or 210TB, have replaced them.

AWS Snowball Edge is an enhanced version of the original AWS Snowball device and it's perfect for a one-time movement of 70 TB of on-premise data into AWS S3. Here's why Snowball Edge is considered the best solution in this scenario and how it differs from the original Snowball devices:

Enhanced Functionality: Snowball Edge offers additional functionality compared to the original Snowball devices. In addition to data transfer capabilities, Snowball Edge devices also provide local compute and storage capabilities. This enables you to perform edge computing tasks and run AWS Lambda functions on the device itself, reducing the need for separate hardware in certain use cases.

Local Data Processing: Snowball Edge allows you to process data locally on the device before transferring it to AWS. This can be beneficial when you have specific data processing requirements or when you want to preprocess the data before storing it in S3. By leveraging Snowball Edge's compute capabilities, you can perform data transformation, data filtering, or any other data processing tasks directly on the device.

Edge Computing Use Cases: Snowball Edge's local compute capabilities make it well-suited for edge computing use cases where low-latency data processing is required at the edge of the network. It enables running applications, performing analytics, or running custom code on the device itself, which is particularly useful in scenarios with limited or intermittent connectivity.

Increased Storage Capacity: Snowball Edge devices have higher storage capacity compared to the original Snowball devices. While the original Snowball devices offer up to 80 TB of storage, Snowball Edge devices provide storage options of up to 80 TB or 210 TB, depending on the device model. This increased storage capacity allows you to accommodate larger data sets within a single device. Note that these device storage sizes may change. 80TB and 210TB are July 2023 specs.

Data Transfer Speed and Security: Similar to the original Snowball devices, Snowball Edge offers fast data transfer rates to expedite the movement of large amounts of data. It also ensures data security with built-in encryption capabilities, tamper-evident enclosures, and secure shipping to AWS data centers.

AWS Snowball Edge is the best solution for a one-time movement of on-premise data into AWS S3 due to its enhanced functionality, local data processing capabilities, and increased storage capacity. The additional capabilities of Snowball Edge differentiate it from the original Snowball devices, offering a more versatile and powerful solution for certain data transfer and edge computing requirements.

--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question125:"link"


