---
layout: default 
title: "914 - It is expected that only certain specifi"
link: "https://www.exam-answer.com/amazon/SAA-C03/question131"
keywords: S3, signedurl, signed, expiration, presigned, presignedurl
---


[.question]
== 914-64a1fa64f053625db51dde74.


****

[.query]
--

You are running a contest and you want users to upload their funniest cat photos. The funniest photo will win a one million dollar prize!

Your only concern is to cut off all uploads at midnight on Sunday night.

What is the easiest way to limit the amount of time customers can upload images of their felines to the S3 bucket?

--

[.list]
--
* [ ] A. Use signed cookies that expire on Sunday night.
* [*] B. Give users a pre-signed URL that points to the S3 bucket.
* [ ] C. Give users a public S3 URL that is associted with signed cookies.
* [*] D. Set an expiration date on the pre-signed URL given to clients.

--
****

[.answer]
Correct Answer  BD

[.explanation]
--
One of the easiest ways to limit the amount of time customers can upload images to an S3 bucket is by utilizing a pre-signed URL with an expiration time. Here's how it works:

Generate a Pre-signed URL: Using the AWS SDK or AWS CLI, you can generate a pre-signed URL for uploading objects to your S3 bucket. The pre-signed URL includes a time-limited access token that grants temporary permission to upload objects.

Set Expiration Time: When generating the pre-signed URL, you can specify an expiration time for the URL. This defines the window during which customers can upload images. Once the expiration time has passed, the pre-signed URL becomes invalid, and further uploads using that URL will be denied.

Provide the Pre-signed URL to Customers: Share the generated pre-signed URL with your customers, either through your application or any other communication channel. Customers can use this URL to directly upload images to your S3 bucket within the specified time frame.

Handle Expiration: Once the expiration time is reached, the pre-signed URL becomes inactive, and any attempts to use it for uploading will fail. You can control the expiration time to align with your desired time limit for image uploads.

By utilizing pre-signed URLs with an expiration time, you can easily control the duration within which customers can upload images to your S3 bucket. This method provides a secure and efficient way to limit the upload window without requiring complex custom logic or additional infrastructure.
--

[.ka]
DCO
'''



https://www.exam-answer.com/amazon/SAA-C03/question131:"link"


