---
layout: default 
title: "805 - You host a static website in an S3 bucke"
---


[.question]
== 805-64a1fa3cf053625db51dddf7.


****

[.query]
--
You host a static website in an S3 bucket, and there are global clients from multiple regions.
You want to use an AWS service to store cache for frequently accessed content so that the latency is reduced and the data transfer rate increases.
Which of the following options would you choose?


--

[.list]
--
* [*] A. Use AWS SDKs to horizontally scale parallel requests to the Amazon S3 service endpoints.
* [ ] B. Create multiple Amazon S3 buckets and put Amazon EC2 and S3 in the same AWS Region.
* [*] C. Enable Cross-Region Replication to several AWS Regions to serve customers from different locations.
* [*] D. Configure CloudFront to deliver the content in the S3 bucket.

--
****

[.answer]
Correct Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - D.
CloudFront can store the frequently accessed content as a cache, and the performance is optimized.
Other options may help with the performance.
However, they do not store cache for the S3 objects.
Option A is incorrect: This option may increase the throughput.
However, it does not store cache.
Option B is incorrect: Because this option does not use cache.
Option C is incorrect: This option creates multiple S3 buckets in different regions.
It does not improve the performance using cache.
Option D is CORRECT: Because CloudFront caches copies the S3 files in its edge locations.
Users are routed to the edge location that has the lowest latency.
The best option for this scenario would be to configure Amazon CloudFront to deliver the content in the S3 bucket.
CloudFront is a Content Delivery Network (CDN) that can cache content at edge locations around the world to reduce latency and improve data transfer rates. When a user requests content from your website, CloudFront will automatically route the request to the nearest edge location, which will serve the cached content if available. If the content is not cached, CloudFront will retrieve it from the origin (in this case, the S3 bucket) and cache it for future requests.
Using AWS SDKs to horizontally scale parallel requests to the Amazon S3 service endpoints, as suggested in option A, may increase the number of requests that S3 can handle simultaneously, but it will not reduce the latency or improve data transfer rates for global clients.
Creating multiple Amazon S3 buckets and putting Amazon EC2 and S3 in the same AWS Region, as suggested in option B, may improve performance for clients within the same region as the EC2 instances and S3 buckets, but it will not improve performance for clients in other regions.
Enabling Cross-Region Replication to several AWS Regions to serve customers from different locations, as suggested in option C, may improve availability and durability by replicating data to multiple regions, but it will not reduce the latency or improve data transfer rates for global clients.
Therefore, the best option to reduce latency and improve data transfer rates for global clients accessing a static website hosted in an S3 bucket is to configure CloudFront to deliver the content in the S3 bucket.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question5:"link"


