---
layout: default 
title: "905 - You are working as an AWS consultant in "
link: "https://www.exam-answer.com/amazon/SAA-C03/question122"
---


[.question]
== 905-64a1fa61f053625db51dde6b.


****

[.query]
--
You are working as an AWS consultant in an E-Commerce organization.
Your organization is planning to migrate its database from on-premises data centers to Amazon RDS.
The automated backup helps to restore the Database to any specific time during the backup retention period in Amazon RDS.
Which of the following actions are performed as a part of the Amazon RDS automated backup process?


--

[.list]
--
* [*] A. AWS creates a storage volume snapshot of the database instance during the backup window once a day. AWS RDS also captures transactions logs and uploads them to S3 buckets every 5 minutes.
* [ ] B. AWS creates a full snapshot of the database every 12 hours during the backup window, captures transactions logs throughout the day, and stores them in S3 buckets.
* [*] C. AWS creates a full daily snapshot during the backup window. With the snapshot, the RDS instance can be restored at any time.
* [ ] D. AWS creates a storage volume snapshot of the database instance every 12 hours during the backup window, captures transactions logs throughout the day, and stores them in S3 buckets.

--
****

[.answer]
A

[.explanation]
--
Volume snapshots during a predefined backup window along iwth transactions logs uploaded to S3 during the day is the way to go. Let's break it down:

Storage Volume Snapshot: AWS creates a snapshot of the storage volume associated with the database instance. This snapshot captures the state of the entire database at a specific point in time. By taking snapshots during the backup window (a defined time period), AWS ensures that backups are performed regularly. Typically, snapshots are taken once a day.

Transaction Logs: In addition to the storage volume snapshot, AWS RDS captures transaction logs of the database. Transaction logs record the changes made to the database over time, including insertions, updates, and deletions. These logs are crucial for maintaining data consistency and enabling point-in-time recovery.

Upload to S3 Buckets: The captured transaction logs are uploaded to S3 (Simple Storage Service) buckets. Amazon S3 is a scalable and durable object storage service provided by AWS. By storing the transaction logs in S3 buckets, they are securely stored and readily available for future use.

The combination of storage volume snapshots and transaction logs ensures comprehensive backups of the database. The snapshots provide a restore point for the entire database, while the transaction logs enable recovery to a specific moment in time by applying the logged changes. This approach allows for data protection, disaster recovery, and the ability to restore the database to a consistent state, even in the event of hardware failure, human error, or other issues.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question122:"link"


