---
layout: default 
title: "911 - You currently have your EC2 instances ru"
link: "https://www.exam-answer.com/amazon/SAA-C03/question128"
keywords: NAT, EC2, AZ, EC2
---


[.question]
== 911-64a1fa63f053625db51dde71.


****

[.query]
--

You have multiple EC2 instances in multiple availability zones within a single region.

How would you set up NAT gateways to allow the EC2 instances access to the Internet.


--

[.list]
--
* [ ] A. Configure a single NAT gateway at the regional level.
* [ ] B. Configure a single NAT gateway in front of an elastic load balancer at the region level.
* [*] C. Create a NAT gateway in each AZ that hosts the EC2 instances.
* [ ] D. A NAT gateway is not required in this scenario.

--
****

[.answer]
Correct Answer  C

[.explanation]
--
When you have EC2 instances running in multiple Availability Zones (AZs) within a Virtual Private Cloud (VPC) in AWS, you need to create a NAT (Network Address Translation) gateway in each AZ to allow those EC2 instances to access the internet. Here's why:

Outbound Internet Access: By default, instances in a private subnet within a VPC cannot communicate directly with the internet. They require a NAT gateway to enable outbound internet access. A NAT gateway acts as a bridge between the private subnet and the internet, allowing instances to send requests to the internet and receive responses.

AZ-specific Routing: Each NAT gateway is associated with a specific AZ. It resides in a specific subnet within the AZ and has an Elastic IP address assigned to it. The NAT gateway acts as the internet gateway for instances in that specific AZ. By creating a NAT gateway in each AZ, you ensure that instances in each AZ have their own dedicated gateway for outbound internet access.

Separate Elastic IP per NAT Gateway: Each NAT gateway requires an Elastic IP address, which serves as a public IP for outbound internet communication. By having a NAT gateway in each AZ, you can assign separate Elastic IP addresses to each gateway. This allows instances in different AZs to have distinct public IP addresses when accessing the internet, enabling proper routing and identification.


When you have EC2 instances running in multiple AZs within a VPC, creating a NAT gateway in each AZ is necessary to provide outbound internet access for instances in each AZ.
--

[.ka]
DRA

'''



