---
layout: default 
title: "916 - You own a MySQL RDS instance in AWS Regi"
link: "https://www.exam-answer.com/amazon/SAA-C03/question133"
keywords: multiaz, rds, replicas, readreplicas
---


[.question]
== 916-64a1fa64f053625db51dde76.


****

[.query]
--
What is the best and easiest way to enhance database access performance for users in Europe who frequently query an RDS database that is hosted in the US?

--

[.list]
--
* [ ] A. Create a read-replica of the database in an AWS region in Europe
* [ ] B. Take a snapshot of the database and then run the snapshot as new RDS database instance in Europe
* [ ] C. Configure read-only Multi-AZ instances in Europe
* [ ] D. Configure CloudFront to cache database requests across Europe

--
****

[.answer]
A

[.explanation]
--

The best way to improve read access to a database is to create a read-replica of the database.

Read replicas of a simple, single RDS instance can be placed in any AWS region across the globe. 

Multi-AZ databases are great, but read replica configuration becomes a bit more complicated.

"Currently, you can't create a Multi-AZ DB cluster read replica from an existing Multi-AZ DB cluster."

--

[.ka]
DHP

'''



https://www.exam-answer.com/amazon/SAA-C03/question133:"link"


