---
layout: default 
title: "859 - You have developed a new web application"
---


[.question]
== 859-64a1fa50f053625db51dde35.


****

[.query]
--
You have developed a new web application on AWS for a real estate firm.
It has a web interface where real estate employees upload photos of newly constructed houses in S3 buckets.
Prospective buyers log in to the website and access photos.
The marketing team has initiated an intensive marketing event to promote new housing schemes which will lead to customers who frequently access these images.
As this is a new application, you have no projection of traffic on the S3 bucket.
You need an S3 storage class that can automatically optimize the storage costs with changing access patterns.
Which of the following is a recommended storage solution to meet this requirement?


--

[.list]
--
* [*] A. Use One Zone-IA storage class to store all images.
* [ ] B. Use Standard-IA to store all images.
* [*] C. Use S3 Intelligent-Tiering storage class.
* [ ] D. Use Standard storage class and use Storage class analytics to identify & move objects using lifecycle policies.

--
****

[.answer]
Correct Answer  C

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - C.
When the access pattern to web applications using S3 storage buckets is unpredictable, you can use S3 intelligent-Tiering storage class.
S3 Intelligent-Tiering storage class includes two access tiers: frequent access and infrequent access.
Based upon access patterns, it moves data between these tiers, which helps in cost saving.
S3 Intelligent-Tiering storage class has the same performance as that of Standard storage class.
Option A is incorrect.
Although it will save costs, it will not provide any protection in case of AZ failure.
Also, this class is suitable for infrequently accessed data &amp; not for frequently access data.
Option B is incorrect as Standard-IA storage class is for infrequently accessed data &amp; there are retrieval charges associated.
In the above requirement, you do not know the data access pattern, which may result in a higher cost.
Option D is incorrect.
It has operational overhead to set up Storage class analytics &amp; moves objects between various classes.
Also, since the access pattern is undetermined, this will run into a costlier option.
For more information on S3 Intelligent-Tiering, refer to the following URLs:
https://aws.amazon.com/blogs/aws/new-automatic-cost-optimization-for-amazon-s3-via-intelligent-tiering/
The recommended storage solution for this scenario is the S3 Intelligent-Tiering storage class (option C).
S3 Intelligent-Tiering is a storage class that uses machine learning to automatically move objects between two access tiers: frequent and infrequent access. It is designed for data with unknown or changing access patterns, such as in this case where there is no projection of traffic on the S3 bucket.
With S3 Intelligent-Tiering, objects that are accessed frequently will be stored in the frequent access tier, which has a higher storage cost but a lower retrieval cost. Objects that are accessed infrequently will be moved to the infrequent access tier, which has a lower storage cost but a higher retrieval cost.
This means that as the marketing event leads to more frequent access to the images, they will be automatically moved to the frequent access tier, and as access patterns change, the storage class will adjust accordingly, optimizing storage costs.
Option A, using the One Zone-IA storage class, is not recommended because it stores data in a single availability zone, making it less resilient to failures.
Option B, using the Standard-IA storage class, is also not recommended because it is optimized for infrequent access, and there is no way to automatically move objects to a more cost-effective storage class if access patterns change.
Option D, using the Standard storage class and using Storage class analytics to identify and move objects using lifecycle policies, is a possible solution, but it requires manual intervention to move objects between storage classes, which may not be optimal for a scenario with changing access patterns.
Therefore, option C, using the S3 Intelligent-Tiering storage class, is the recommended storage solution for this scenario.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question68:"link"


