---
layout: default 
title: "924 - You have an application hosted on AWS co"
link: "https://www.exam-answer.com/amazon/SAA-C03/question141"
---


[.question]
== 924-64a1fa67f053625db51dde7e.


****

[.query]
--

You configured an AWS Scaling Group but your EC2 instances aren't scaling when they should.

What would you check first?

--

[.list]
--
* [ ] A. Make sure health checks are enabled.
* [ ] B. Make sure only one scaling policy is triggered at a time
* [ ] C. Make sure traffic is being sent to the S3 instances.
* [ ] D. Make sure that the right metrics are triggering a policy change

--
****

[.answer]
Correct Answer  D

[.explanation]
--

In this situation, the first thing you should do is check that the right metrics are being monitored.

If you're not monitoring the right metrics, the group won't scale when you need it to.

You can have more than one policy triggered at a time. If that happens, the one with the most impact gets precedence, so that option should not stop auto scaling from working.

Health checks won't impact autoscaling. If a node is unhealthy, AWS will spin up a new instance in its place, regardless of the scaling policy. 

--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question141:"link"


