---
layout: default 
title: "910 - You have a web application hosted on an "
---


[.question]
== 910-64a1fa62f053625db51dde70.


****

[.query]
--
You have a web application hosted on an EC2 Instance in AWS that users can access across the globe.
The Operations team has been receiving support requests about extreme slowness from users in some regions.
What can be done to the architecture to improve the response time for these users?


--

[.list]
--
* [*] A. Add more EC2 Instances to support the load.
* [ ] B. Change the Instance type to a higher instance type.
* [*] C. Add Route 53 health checks to improve the performance.
* [*] D. Place the EC2 Instance behind CloudFront.

--
****

[.answer]
Correct Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - D.
AWS Documentation mentions the following:
Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files to your users.
CloudFront delivers your content through a worldwide network of data centers called edge locations.
When a user requests content that you're serving with CloudFront, the user is routed to the edge location that provides the lowest latency (time delay) so that content is delivered with the best possible performance.
For more information on Amazon CloudFront, please refer to the below URL:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html
Option A is incorrect.
The latency issue is experienced by people from certain parts of the world only.
So, increasing the number of EC2 Instances or increasing the instance size will not make much difference.
Option B is incorrect.The latency issue is experienced by people from certain parts of the world only.
So, changing the Instance type to a higher instance type will not make much difference.
Option C is incorrect.
Route 53 health checks are meant to see whether the instance status is healthy or not.
Since this case deals with responding to users' requests, we do not have to worry about this.
However, for improving latency issues, CloudFront is a good solution.
The best answer to improve response time for users across the globe would be to place the EC2 instance behind CloudFront, which is option D.
CloudFront is a content delivery network (CDN) service provided by AWS. It caches and delivers content from various AWS services, including EC2 instances, to users from a network of global edge locations. When a user requests content, CloudFront delivers the cached content from the edge location closest to the user, reducing the latency and improving the response time.
Adding more EC2 instances, as suggested in option A, may help to support the load, but it will not necessarily improve the response time for users in different regions. Additionally, it may add unnecessary cost to the architecture.
Changing the instance type to a higher instance type, as suggested in option B, may help to improve the performance of the EC2 instance, but it will not necessarily address the issue of extreme slowness reported by users in different regions.
Option C suggests adding Route 53 health checks to improve performance, but Route 53 health checks are used to monitor the health of resources and redirect traffic in case of a failure. They do not necessarily improve the response time for users in different regions.
In summary, placing the EC2 instance behind CloudFront is the best option to improve the response time for users across the globe. CloudFront will deliver cached content from the edge location closest to the user, reducing latency and improving the response time.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question127:"link"


