---
layout: default 
title: "1276 - As a Cloud Architect you have deployed a"
---


[.question]
== 1276-64a1fb09f053625db51de01f.


****

[.query]
--
As a Cloud Architect, you have deployed an existing application from the local server to an On-demand EC2 instance.
You found out that there is an issue while connecting the application using the HTTPS Protocol.
After troubleshooting the issue, you added port 443 to the security group of the instance.
How much time will it take to update changes to all of the resources related to Security groups?


--

[.list]
--
* [*] A. It can take up to 10 minutes depending on the number of resources.
* [ ] B. You just need to restart the EC2 Server.
* [*] C. You cannot make any change to existing security group, you have to create new Security group.
* [*] D. Immediately without restart.
* [ ] E. You have to deploy your application again.

--
****

[.answer]
Correct Answer  D

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
E.
Correct Answer - D.
You can assign a security group to an instance when you launch the instance.
When you add or remove rules, those changes are automatically applied to all instances to which you've assigned the security group.
Option A is incorrect.
Any changes made to the Security Group are immediately effected.
Option B is incorrect because you don't need to restart the server to check any Security Group updates.
Option C is incorrect because you can modify rules in the security group.
Option D is CORRECT because any changes made to the security group are taken into effect immediately.
Option E is incorrect because this security group works at the instance level, not at the application level.
Reference:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html#adding-security-group-rule https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/working-with-security-groups.html
When you add a new port or modify the rules of an existing Security Group in Amazon Web Services (AWS), the changes are propagated to all the instances associated with that Security Group. However, the time it takes for the changes to take effect can vary based on multiple factors.
Option A is partially correct. It is true that the time it takes for the changes to take effect depends on the number of resources, but it is not the only factor. The changes can take anywhere from a few seconds to several minutes, depending on the number of instances, the size of the Security Group, and the AWS Region.
Option B is incorrect because restarting the EC2 instance is not necessary to apply the changes to the Security Group.
Option C is also incorrect. You can modify the rules of an existing Security Group. You don't have to create a new one.
Option D is partially correct. The changes to the Security Group should take effect immediately. However, it may take some time for the instances to start using the updated rules.
Option E is incorrect. You don't have to redeploy the application to apply changes to the Security Group.
In summary, the correct answer is Option A. The time it takes for the changes to take effect depends on multiple factors, including the number of instances and the size of the Security Group. It can take anywhere from a few seconds to several minutes.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question561:"link"


