---
layout: default 
title: "920 - An application team needs to quickly pro"
link: "https://www.exam-answer.com/amazon/SAA-C03/question137"
keywords: beanstalk, developers
---


[.question]
== 920-64a1fa65f053625db51dde7a.



****

[.query]
--

Your developers want to quickly deploy a web based Java application that needs a Microsoft SQL Server instance for persistence.

What's the fastest and easiest way for a developer to create an environment that supports this setup.

--

[.list]
--
* [ ] A. Start an on-demand EC2 instance and install the software required to support Java and MS SQL Server
* [ ] B. Find a suitable AMI with MS SQL Server and a Java support and deploy as a spot EC2 instance
* [ ] C. Use Elastic Beanstalk to provision an environment that supports Java and an AWS managed MS SQL Server instance
* [ ] D. Deploy two EC2 AMIs, one which supports the Java application and a second that supports MS SQL Server

--
****

[.answer]
Correct Answer  C

[.explanation]
--
Elastic Beanstalk is the fastest and easiest way to get a configuration like this going.

AWS Elastic Beanstalk makes it easy for devs to quickly deploy applications in AWS.

With very little cloud experience, developers can deploy applications that are written in .NET, PHP, Node.js, Python, Ruby, Go, and Docker.

Plus, AWS Elastic Beanstalk provides support for various databases such as Amazon RDS, DynamoDB, Microsoft SQL Server, Oracle, or other relational databases running on Amazon EC2.

--

[.ka]
DCO

'''



https://www.exam-answer.com/amazon/SAA-C03/question137:"link"


