---
layout: default 
title: "901 - You have an S3 bucket that receives phot"
link: "https://www.exam-answer.com/amazon/SAA-C03/question116"
---


[.question]
== 901-64a1fa5ff053625db51dde65.


****

[.query]
--
You have an S3 bucket that receives photos uploaded by customers.
When an object is uploaded, an event notification is sent to an SQS queue with the object details.
You also have an ECS cluster that gets messages from the queue to do the batch processing.
Each of the batch processing job takes the same amount of time to get executed.
The queue size may change greatly depending on the number of incoming messages and backend processing speed.
Which metric would you use to scale up/down the ECS cluster capacity?


--

[.list]
--
* [*] A. The number of messages in the SQS queue.
* [ ] B. Memory usage of the ECS cluster.
* [*] C. Number of objects in the S3 bucket.
* [ ] D. Number of containers in the ECS cluster.

--
****

[.answer]
Correct Answer  A

[.explanation]
--
The metric that could be used to scale up/down the ECS cluster capacity in this scenario is the queue size or queue length.

Since the queue receives event notifications for each uploaded object, the size of the queue represents the number of messages waiting to be processed by the ECS cluster. By monitoring the queue size, you can determine the workload and adjust the capacity of the ECS cluster accordingly.

To scale up the ECS cluster capacity, you can increase the number of ECS instances or tasks to handle a larger queue size. This ensures that the batch processing jobs can be executed efficiently without any backlog.

Conversely, if the queue size decreases and the workload reduces, you can scale down the ECS cluster capacity by decreasing the number of instances or tasks. This helps to optimize resource utilization and reduce costs when the demand is lower.

By using the queue size as a metric for scaling, you can dynamically adjust the capacity of the ECS cluster based on the workload and ensure efficient processing of the incoming messages from the SQS queue.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question116:"link"


