---
layout: default 
title: "904 - You are designing a website for a compan"
link: "https://www.exam-answer.com/amazon/SAA-C03/question120"
---


[.question]
== 904-64a1fa60f053625db51dde69.


****

[.query]
--
You are designing a website for a company that streams anime videos.
You serve this content through CloudFront.
The company has implemented a section for premium subscribers.
This section contains more videos than the free section.
You want to ensure that only premium subscribers can access this premium section.
How can you achieve this easily?


--

[.list]
--
* [ ] A. Using bucket policies.
* [ ] B. Requiring HTTPS for communication between users and CloudFront.
* [ ] C. Using CloudFront origin with signed URLs.
* [*] D. Using CloudFront origin with signed cookies.

--
****

[.answer]
D

[.explanation]
--
Signed cookies are perfect for scenarios where access controls need to be applied to specific parts of a website rather than specific content.

Using CloudFront origin with signed cookies is a method of controlling access to content served through Amazon CloudFront by using signed cookies. It allows you to grant or deny access to specific content based on the presence and validity of cookies.

When you configure CloudFront to use signed cookies, you generate a set of cookies with specific attributes, such as an expiration time, path, and domain. These cookies are then used to authenticate and authorize access to your content.

Here's how the process works:

Configuration: You configure your CloudFront distribution to use signed cookies as the method of access control. This involves specifying the trusted key pair, which consists of a private key used to sign the cookies and a corresponding public key that is stored with CloudFront.

Generating Signed Cookies: Using the private key, you generate a set of signed cookies with the desired attributes. These cookies can contain information such as the expiration time, path, and domain restrictions.

Distribution Behavior: In your CloudFront distribution behavior settings, you specify that the distribution requires the presence of the signed cookies for access. You can define rules based on the specific cookie attributes, such as allowing access only to certain paths or domains.

Cookie Inclusion: When users access your content through CloudFront, they need to include the signed cookies in their requests. This can be done by setting the cookies in the request headers.

Authentication and Authorization: CloudFront validates the signed cookies included in the request against the corresponding public key stored with the distribution. It verifies the signature and checks the attributes to determine if the request meets the specified access rules.

Access Control: Based on the authentication and authorization checks, CloudFront either grants or denies access to the requested content. Users without valid or matching cookies will receive an access denied response.

Using CloudFront origin with signed cookies provides a flexible and secure method to control access to your content. It allows you to implement fine-grained access rules and restrict content based on specific attributes defined in the signed cookies. This approach is particularly useful when you need to provide access to specific users or groups for limited periods or under certain conditions.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question120:"link"


