---
layout: default 
title: "899 - A company is planning on testing a large"
---


[.question]
== 899-64a1fa5ef053625db51dde62.


****

[.query]
--
A company is planning on testing a large set of IoT-enabled devices.
These devices will generate a large amount of data every second.
You need a scalable and durable real-time data streaming service to capture the data generated from these devices.
Which AWS service would be the most appropriate for this purpose?


--

[.list]
--
* [*] A. AWS EMR.
* [*] B. AWS Kinesis Data Streams.
* [*] C. AWS SQS.
* [ ] D. AWS SNS.

--
****

[.answer]
Correct Answer  B

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Correct Answer - B.
AWS Documentation mentions the following on Amazon Kinesis:
Amazon Kinesis makes it easy to collect, process, and analyze real-time, streaming data so you can get timely insights and react quickly to new information.
Amazon Kinesis offers key capabilities to cost-effectively process streaming data at any scale, along with the flexibility to choose the tools that best suit the requirements of your application.
With Amazon Kinesis, you can ingest real-time data such as video, audio, application logs, website clickstreams, and IoT telemetry data for machine learning, analytics, and other applications.
For more information on Amazon Kinesis, please refer to the below URL:
https://aws.amazon.com/kinesis/
Option A is incorrect.
Amazon EMR can be used to process applications with data-intensive workloads but is not a data streaming service.
Option B is correct.
Amazon Kinesis can be used to store, process, and analyze real-time streaming data.
Option C is incorrect.
SQS is a fully managed message queuing service.
But it cannot be configured as a real-time data streaming service.
Option D is incorrect.
SNS is a flexible, fully managed pub/sub messaging and mobile notifications service instead of a data streaming service.
The most appropriate AWS service for capturing real-time data generated from IoT-enabled devices is AWS Kinesis Data Streams, option B.
AWS Kinesis Data Streams is a scalable and durable real-time data streaming service that can handle large amounts of data generated by IoT devices. It is designed to capture, store, and process streaming data in real-time. Kinesis Data Streams allows you to collect, process, and analyze data from hundreds of thousands of sources, such as IoT devices, and provides sub-second latency for real-time analytics.
EMR (Elastic Map Reduce), option A, is a managed Hadoop framework that is used for processing large amounts of data. It is typically used for batch processing of data rather than real-time data streaming.
SQS (Simple Queue Service), option C, is a fully-managed message queuing service that enables decoupling of components within a distributed application. SQS can be used to decouple the message producer from the message consumer, but it is not a real-time data streaming service.
SNS (Simple Notification Service), option D, is a fully-managed notification service that can be used to send messages or notifications to multiple recipients, such as email or SMS. SNS is not a real-time data streaming service.
In summary, AWS Kinesis Data Streams is the most appropriate service for capturing and processing real-time data generated from IoT-enabled devices, due to its scalability, durability, and sub-second latency capabilities.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/SAA-C03/question113:"link"


